---
apiVersion: v1
kind: Service
metadata:
  name: nas01
  namespace: external-ingresses
spec:
  type: ExternalName
  externalName: nas01.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas01
  namespace: external-ingresses
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nas01.crt.house
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx-internal
  rules:
  - host: nas01.crt.house
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nas01
            port:
              number: 5001
  tls:
  - hosts:
    - nas01.crt.house
