---
apiVersion: v1
kind: Service
metadata:
  name: zigbee
  namespace: external-ingresses
spec:
  type: ExternalName
  externalName: 192.168.1.250
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee
  namespace: external-ingresses
  annotations:
    external-dns.alpha.kubernetes.io/hostname: zigbee.crt.house
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx-internal
  rules:
  - host: zigbee.crt.house
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zigbee
            port:
              number: 443
  tls:
  - hosts:
    - zigbee.crt.house
