---
apiVersion: v1
kind: Service
metadata:
  name: {{NAME}}
  namespace: external-ingresses
spec:
  type: ExternalName
  externalName: {{NAME}}.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{NAME}}
  namespace: external-ingresses
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{NAME}}.crt.house
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx-internal
  rules:
  - host: {{NAME}}.crt.house
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{NAME}}
            port:
              number: {{PORT}}
  tls:
  - hosts:
    - {{NAME}}.crt.house
